apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: resources-state-store
  namespace: default
spec:
  type: state.mongodb
  metadata:
  - name: host
    value: "megaphone-mongodb.mongo.cosmos.azure.com:10255"
  - name: username
    value: megaphone-mongodb
  - name: password
    secretKeyRef:
      name: megaphone-mongo-pwd
  - name: databaseName
    value: "megaphone"
  - name: collectionName
    value: "resources"
auth:
    secretStore: azurekeyvault
scopes:
  - resources-service