version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for nuget
  - package-ecosystem: "nuget"
    directory: "src/Standard/Standard"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "src/Standard/Standard.Tests"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "dapr/src/API/Megaphone.API"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "dapr/src/Crawler/Crawler"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "dapr/src/Crawler/Crawler.API"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "dapr/src/Crawler/Crawler.Tests"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "dapr/src/Feeds/Feeds.API"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "dapr/src/Resources/Resource.Actor"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "dapr/src/Resources/Resource.Actor.Interface"
    schedule:
      interval: "daily"
      