# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  crawler:
    image: crawler
    build:
      context: .
      dockerfile: src/Crawler/Crawler.API/Dockerfile
    ports:
      - 80