apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: crawler-commands
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  scopes:
  - crawler-service
  - list-service
