apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: feed-state-store
  namespace: default
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
scopes:
  - feed-service