apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: resources-state-store
  namespace: default
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
scopes:
  - resources-service
  - crawler-service