apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: crawl-requests
  namespace: default
spec:
  type: bindings.rabbitmq
  metadata:
  - name: queueName
    value: "crawl-queue"
  - name: host
    value: "amqp://guest:guest@rabbitmq:5672"
  - name: durable
    value: true
  - name: deleteWhenUnused
    value: false
  - name: ttlInSeconds
    value: 600
scope:
  - crawler