name: Resources Build

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/Resources/**'
      
jobs:
  build:
    name: Resources - Build
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/AlexandreBrisebois/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install dependencies
      run: dotnet restore ./src/Resources/Resources.sln
    - name: Build
      run: dotnet build ./src/Resources/Resources.sln --configuration Release --no-restore