name: Standard Build

on:
  push:
    paths:
      - 'src/Standard/**'
  pull_request:
    paths:
      - 'src/Standard/**'
           
jobs:
  build:
    name: Standard - Build & Test
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/AlexandreBrisebois/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install dependencies
      run: dotnet restore ./src/Standard/Standard.sln
    - name: Build
      run: dotnet build ./src/Standard/Standard.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/Standard/Standard.Tests/Standard.Tests.csproj --no-restore --verbosity normal
